//dart is clint-optimize side language
//for fast apps any platform...
//dart is a programming language....
//
String callHello = 'hello World'; // this variable is global variable ,,,
void main() {
  print(
      '$callHello it is ${callHello.runtimeType} type '); //print hello world ...
}
